version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: medusa_postgres
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: medusa_redis
    ports:
      - "6379:6379"

  medusa:
    build: ./backend
    container_name: medusa_backend
    environment:
      DATABASE_URL: postgres://medusa:medusa@postgres:5432/medusa_db
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
